CREATE SCHEMA IF NOT EXISTS prueba_evento;
SET search_path TO prueba_evento, public;

-- ==========================================================
-- 1. TABLAS PRINCIPALES
-- ==========================================================

CREATE TABLE IF NOT EXISTS obras (
    id_obra SERIAL PRIMARY KEY,
    nombre_obra VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS especialidades (
    id_especialidad SERIAL PRIMARY KEY,
    nombre_especialidad VARCHAR(50) NOT NULL 
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario SERIAL PRIMARY KEY,
    tipo_documento VARCHAR(5) NOT NULL,
    numero_documento VARCHAR(20) NOT NULL,
    nombre_completo VARCHAR(50) NOT NULL,
    celular VARCHAR(10) NOT NULL,
    email VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    sexo CHAR(1) CONSTRAINT chk_sexo CHECK (sexo IN ('M', 'F')),
    lugar_residencia VARCHAR(25),
    ocupacion VARCHAR(15),
    metodo_registro VARCHAR(20),
    preferencia_contacto VARCHAR(20),
    fecha_hora_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    autorizacion_tratamiento_datos BOOLEAN DEFAULT FALSE NOT NULL,
    CHECK (celular ~ '^[0-9]{10}$'),
    CONSTRAINT unq_documento_usuario UNIQUE (tipo_documento, numero_documento)
);

-- ==========================================================
-- 2. TABLAS SECUNDARIAS
-- ==========================================================

CREATE TABLE IF NOT EXISTS eventos (
    id_evento INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1) PRIMARY KEY,
    id_obra INTEGER REFERENCES obras(id_obra) ON DELETE RESTRICT,
    nombre_evento VARCHAR(50) NOT NULL,
    lugar_evento VARCHAR(50) NOT NULL,
    fecha_evento DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS servicios (
    id_servicio SERIAL PRIMARY KEY, 
    fk_id_obra INTEGER REFERENCES obras(id_obra) ON DELETE RESTRICT,
    id_especialidad INTEGER REFERENCES especialidades(id_especialidad) ON DELETE RESTRICT, 
    nombre_servicio VARCHAR(50) NOT NULL 
);

CREATE TABLE IF NOT EXISTS evento_especialidades (
    id_configuracion SERIAL PRIMARY KEY,
    id_evento INTEGER REFERENCES eventos(id_evento) ON DELETE CASCADE,
    id_especialidad INTEGER REFERENCES especialidades(id_especialidad) ON DELETE CASCADE,
    CONSTRAINT unq_evento_especialidad UNIQUE (id_evento, id_especialidad)
);

-- ==========================================================
-- 3. CATÁLOGO Y CONFIGURACIÓN DE EXPERIENCIAS VID
-- ==========================================================

-- Catálogo de Experiencias/Actividades
CREATE TABLE IF NOT EXISTS experiencias (
    id_experiencia SERIAL PRIMARY KEY,
    nombre_experiencia VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255)
);

-- Asociación de qué experiencias están habilitadas en cada evento
CREATE TABLE IF NOT EXISTS evento_experiencias (
    id_configuracion SERIAL PRIMARY KEY,
    id_evento INTEGER REFERENCES eventos(id_evento) ON DELETE CASCADE,
    id_experiencia INTEGER REFERENCES experiencias(id_experiencia) ON DELETE CASCADE,
    CONSTRAINT unq_evento_experiencia UNIQUE (id_evento, id_experiencia)
);

-- Registro de participación directa del usuario en experiencias del evento
CREATE TABLE IF NOT EXISTS participacion_experiencias (
    id_participacion SERIAL PRIMARY KEY,
    id_evento INTEGER REFERENCES eventos(id_evento) ON DELETE CASCADE,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    id_experiencia INTEGER REFERENCES experiencias(id_experiencia) ON DELETE CASCADE,
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unq_participacion_usuario_evento_exp UNIQUE (id_evento, id_usuario, id_experiencia)
);

-- ==========================================================
-- 4. TABLAS TRANSACCIONALES (STANDS Y ATENCIÓN CLÍNICA)
-- ==========================================================

CREATE TABLE IF NOT EXISTS interacciones_evento (
    id_interaccion SERIAL PRIMARY KEY,
    id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE, 
    id_obra INTEGER REFERENCES obras(id_obra) ON DELETE RESTRICT, 
    id_profesional VARCHAR(11) NOT NULL,
    id_especialidad INTEGER REFERENCES especialidades(id_especialidad) ON DELETE RESTRICT,
    servicio_recomendado INTEGER REFERENCES servicios(id_servicio) ON DELETE RESTRICT, 
    observaciones TEXT,
    id_evento INTEGER REFERENCES eventos(id_evento) ON DELETE RESTRICT,
    fecha_hora_atencion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado_evaluacion VARCHAR(50),
    CONSTRAINT uniq_interaccion_evento_usuario UNIQUE (id_evento, id_usuario, id_especialidad) 
);

CREATE TABLE IF NOT EXISTS datos_clinicos (
    id_tamizaje SERIAL PRIMARY KEY,
    id_interaccion INTEGER REFERENCES interacciones_evento(id_interaccion) ON DELETE CASCADE UNIQUE,
    peso NUMERIC(5, 2), 
    estatura INTEGER, 
    imc NUMERIC(4, 2), 
    fumador BOOLEAN,
    presion_arterial VARCHAR(10),  
    glicemia NUMERIC(5, 2),         
    dislipidemia VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS seguimiento_tamizaje (
    id_seguimiento SERIAL PRIMARY KEY,
    id_interaccion INTEGER REFERENCES interacciones_evento(id_interaccion) ON DELETE CASCADE,
    id_servicio INTEGER REFERENCES servicios(id_servicio) ON DELETE RESTRICT,
    fecha_servicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================================
-- 5. ÍNDICES DE LLAVES FORÁNEAS Y CONSULTAS
-- ==========================================================

CREATE INDEX IF NOT EXISTS idx_interacciones_usuario ON interacciones_evento(id_usuario);
CREATE INDEX IF NOT EXISTS idx_interacciones_evento ON interacciones_evento(id_evento);
CREATE INDEX IF NOT EXISTS idx_interacciones_obra ON interacciones_evento(id_obra);
CREATE INDEX IF NOT EXISTS idx_seguimiento_interaccion ON seguimiento_tamizaje(id_interaccion);
CREATE INDEX IF NOT EXISTS idx_seguimiento_servicio ON seguimiento_tamizaje(id_servicio);
CREATE INDEX IF NOT EXISTS idx_servicios_obra ON servicios(fk_id_obra);

CREATE INDEX IF NOT EXISTS idx_participacion_usuario ON participacion_experiencias(id_usuario);
CREATE INDEX IF NOT EXISTS idx_participacion_evento ON participacion_experiencias(id_evento);
CREATE INDEX IF NOT EXISTS idx_evento_experiencias_evento ON evento_experiencias(id_evento);

-- Índices de negocio
CREATE INDEX IF NOT EXISTS idx_interacciones_profesional ON interacciones_evento(id_profesional);
CREATE INDEX IF NOT EXISTS idx_interacciones_servicio_rec ON interacciones_evento(servicio_recomendado);
CREATE INDEX IF NOT EXISTS idx_interacciones_hora ON interacciones_evento(fecha_hora_atencion);
CREATE INDEX IF NOT EXISTS idx_eventos_lugar ON eventos(lugar_evento);
CREATE INDEX IF NOT EXISTS idx_eventos_fecha ON eventos(fecha_evento);

-- Índices de perfilamiento
CREATE INDEX IF NOT EXISTS idx_usuarios_metodo ON usuarios(metodo_registro);
CREATE INDEX IF NOT EXISTS idx_usuarios_nacimiento ON usuarios(fecha_nacimiento);
CREATE INDEX IF NOT EXISTS idx_usuarios_residencia ON usuarios(lugar_residencia);
CREATE INDEX IF NOT EXISTS idx_usuarios_sexo ON usuarios(sexo);
CREATE INDEX IF NOT EXISTS idx_usuarios_contacto ON usuarios(preferencia_contacto);

-- ==========================================================
-- 6. CONSULTAS Y OPERACIONES DE EJEMPLO
-- ==========================================================

-- Buscar usuario por documento
SELECT nombre_completo
FROM usuarios u 
WHERE u.numero_documento = '';

-- Insertar o actualizar datos de usuario (Upsert)
INSERT INTO usuarios (
    tipo_documento,
    numero_documento,
    nombre_completo,
    celular,
    email,
    fecha_nacimiento,
    sexo,
    metodo_registro,
    autorizacion_tratamiento_datos
)
VALUES (
    'CC',
    '1234567890',
    'Juan Perez',
    '3001234567',
    'juan@example.com',
    '1990-01-01',
    'M',
    'Web',
    TRUE
)
ON CONFLICT (tipo_documento, numero_documento)
DO UPDATE SET 
    nombre_completo = EXCLUDED.nombre_completo,
    celular = EXCLUDED.celular,
    email = EXCLUDED.email,
    fecha_nacimiento = EXCLUDED.fecha_nacimiento;

-- Insertar obra de ejemplo
INSERT INTO obras (nombre_obra) 
VALUES ('Cardiovid');

-- Insertar experiencias iniciales de catálogo
INSERT INTO experiencias (nombre_experiencia, descripcion) VALUES
('Donante de sangre', 'Punto de donación efectiva de sangre'),
('Tienda VID', 'Tienda y souvenirs de la Fundación'),
('Salón de experiencias', 'Espacio de bienestar y relajación'),
('Biodanza', 'Sesión de expresión corporal y danza'),
('Tejedores', 'Taller de tejido manual'),
('Mapa de los sueños', 'Actividad de proyección y sueños'),
('Charla médica', 'Espacio de capacitación en salud'),
('Enfoque TAICHI', 'Taller de respiración y Tai Chi'),
('Yoga', 'Sesión de relajación y yoga guiado');
